version: 2

models:
  - name: int_campaigns
    description: "Tüm reklam kampanyalarından gelen birleşik veriler"

    columns:
      - name: paid_source
        description: "Kaynak (adwords, bing, criteo, facebook)"
        tests:
          - not_null

      - name: campaign_name
        description: "Kampanya adı"
        tests:
          - not_null

      - name: campaign_key
        description: "Kampanya benzersiz anahtarı"
        tests:
          - not_null

      - name: date_date
        description: "Tarih"
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - campaign_key
              - date_date


  - name: int_campaigns_day
    description: "Günlük toplu kampanya verisi"
    columns:
      - name: date_date
        description: "Tarih"
        tests:
          - not_null

      - name: ads_cost
        description: "Günlük toplam reklam harcaması"
        tests:
          - not_null

      - name: ads_impression
        description: "Günlük toplam reklam gösterimi"
        tests:
          - not_null

      - name: ads_clicks
        description: "Günlük toplam tıklama sayısı"
        tests:
          - not_null


